import Head from 'next/head'
import Hero from '../components/Hero'
import Carousel from '../components/Carousel'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Ogram, flexible Staffing and recruiting</title>
      </Head>

      <div className={styles.main}>
        <Hero />
        <Carousel />
      </div>
    </div>
  )
}
